### PR TITLE
Suggestions for intro and outro

### PR DESCRIPTION
**Pull request by duncan**
Refined intro and outro to give a bit more history at the first and to finish on a good solid takeaway.

### CODE REVIEW

**Comment by chad** [comment]
To get closer to your changes we could have two jokey architecture slides. Wunderlist 1 (same picture I have now but PHP & MySQL labeled). Wunderlist 2 (same picture with Rails & Postgres) :)

**Comment by duncan** [comment]
Sure! That'd work.

**Comment by nathan-ms** [comment]
I'm going to copy and paste the take away slide since it is great, but it can't auto merge for some reason.

**Comment by nathan-ms** [comment]
OK, I think I got the gist of what you wanted in master. Instead of making a new sketch file I looked up how to do text beside the image.

**Comment by duncan** [comment]
K. Please do..

**Comment by duncan** [comment]
Looks great! Danke dir. I'll kill this PR.

**Pull request closed without merging**
